spring:
  application:
    name: "@project.name@"
  jpa:
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: none
        show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo_app
    username: postgres
    password: password
  sql:
    init:
      enabled: true
      continue-on-error: true
      platform: postgresql
server:
  port: 40000